{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.0.1.aar",
          "url": "databinding-runtime-7.0.1.aar",
          "size": 62666,
          "sha512": "ae1284115c624625ba701e364fe2690e99954edf4fa71438d6a0e09add8907739b9494892d8e9552291b663ea0d3f124b06897647a0714441ab5b52cdec8b9b4",
          "sha256": "281eb27a05241962bb89d2a7c6d2554990d51ea7749a0e261215560515d1469f",
          "sha1": "eb635824630a977845452beab9b7b2c7319d5b84",
          "md5": "19b066f5ecd8d018568443ac1b3d5731"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.0.1.aar",
          "url": "databinding-runtime-7.0.1.aar",
          "size": 62666,
          "sha512": "ae1284115c624625ba701e364fe2690e99954edf4fa71438d6a0e09add8907739b9494892d8e9552291b663ea0d3f124b06897647a0714441ab5b52cdec8b9b4",
          "sha256": "281eb27a05241962bb89d2a7c6d2554990d51ea7749a0e261215560515d1469f",
          "sha1": "eb635824630a977845452beab9b7b2c7319d5b84",
          "md5": "19b066f5ecd8d018568443ac1b3d5731"
        }
      ]
    }
  ]
}
