{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "databinding-compiler-7.0.1.jar",
          "url": "databinding-compiler-7.0.1.jar",
          "size": 1193240,
          "sha512": "2795468faa728e71434398fac30ad2559d097cc37b55246b80ba09b1e1ed8c3beea8926dc19e74a0cc33c3b197d23b07f2c8f6808c6373bd69dba91362644461",
          "sha256": "fefdbdd1623089337c5049c5f1032fe0ac97502655fc2b900671b0a7ac4634ae",
          "sha1": "a66f5d6a2dde369150d4fbb09ad75ff242f15e7f",
          "md5": "868fbbd82491ea4f693ce2cbe7588619"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-7.0.1.jar",
          "url": "databinding-compiler-7.0.1.jar",
          "size": 1193240,
          "sha512": "2795468faa728e71434398fac30ad2559d097cc37b55246b80ba09b1e1ed8c3beea8926dc19e74a0cc33c3b197d23b07f2c8f6808c6373bd69dba91362644461",
          "sha256": "fefdbdd1623089337c5049c5f1032fe0ac97502655fc2b900671b0a7ac4634ae",
          "sha1": "a66f5d6a2dde369150d4fbb09ad75ff242f15e7f",
          "md5": "868fbbd82491ea4f693ce2cbe7588619"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-7.0.1-javadoc.jar",
          "url": "databinding-compiler-7.0.1-javadoc.jar",
          "size": 757436,
          "sha512": "ec2228aea2bed6cf2d4949b1a888984cd7e250b0a5b5be5b4a8050d439af1ad3917f24fce285a4e68e5df58b3039c6a128eb44cba8a08416d057b4d1584eb386",
          "sha256": "b6a31f713a9d80baad8a460d403b0d2a8dddf1d934aedefad80c661e0a35d228",
          "sha1": "d7ac2e9447ea237204f0c0723fa31d3947e0efb3",
          "md5": "7d8d99bc5da4d88d86e68f2a8d68129a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-7.0.1-sources.jar",
          "url": "databinding-compiler-7.0.1-sources.jar",
          "size": 569317,
          "sha512": "d3c62d130781d3af7c009f1a7605164a2a0569c6d66e88725959707300478186627c1e5889c8f10d1993bd7bdb84370accfd8ecd7ae727a00a923a6f613750bf",
          "sha256": "ce2858d2662756ec4f33c72f3c790019790443dbab28137b93759b10fb529368",
          "sha1": "ab661ec4a9349d675b51dbfd733781645c9a40d2",
          "md5": "61846ed4fca58d046478c600f29c89e5"
        }
      ]
    }
  ]
}
