{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apkzlib-7.0.1.jar",
          "url": "apkzlib-7.0.1.jar",
          "size": 202778,
          "sha512": "f46a8d7835fc5a88e8ae6ab1cab3b6df7ca11a0633ba11b8344dac0a6fea7b726fabf7df80feb85bf81a057daef05bf775b9960d030d41b61dfa8c57a57e4e46",
          "sha256": "1412dd4d73b8a15cd44427cb2236759a2b386d60bd190843236f6dd2808fe9ac",
          "sha1": "6972062e034ed75ac9098e9361df31d80b7a3fb0",
          "md5": "e5d4880c6e0c58a0d2e3b6618e41af34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-7.0.1.jar",
          "url": "apkzlib-7.0.1.jar",
          "size": 202778,
          "sha512": "f46a8d7835fc5a88e8ae6ab1cab3b6df7ca11a0633ba11b8344dac0a6fea7b726fabf7df80feb85bf81a057daef05bf775b9960d030d41b61dfa8c57a57e4e46",
          "sha256": "1412dd4d73b8a15cd44427cb2236759a2b386d60bd190843236f6dd2808fe9ac",
          "sha1": "6972062e034ed75ac9098e9361df31d80b7a3fb0",
          "md5": "e5d4880c6e0c58a0d2e3b6618e41af34"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.0.1-javadoc.jar",
          "url": "apkzlib-7.0.1-javadoc.jar",
          "size": 699285,
          "sha512": "08c7af114ba5e12c3e6235f04f94be40a93df94e6759f8f506f772e310777ca889795d015648ea632b421b1be9d81c584e85348b08c3e50365ea328b37b653be",
          "sha256": "8ef68269029da6d48f1ac38201b7533f9a459b056ec84bd1ff44d1a6a84871bb",
          "sha1": "a890e335b12cd2f1d2540996ffe831c33003fe7a",
          "md5": "241cb2a75fbaa84c71b27f4e85b1d477"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.0.1-sources.jar",
          "url": "apkzlib-7.0.1-sources.jar",
          "size": 175631,
          "sha512": "c609eb6f75164d7ab1f66057ece956f68dc503a8d73e59db5d8cb96cdfe38b271cf6c4af5ba1c3672386d9d13da0baf751d191afa90bab39cc3f851b0fb1044e",
          "sha256": "8c93b0de4303bfdb0039729d930b6a15fadf0291a5d172d2ad738e8fe99545eb",
          "sha1": "022a540038ae137348f845dc7e26d898e2933c73",
          "md5": "a75a507083f4970019c5796377638f5d"
        }
      ]
    }
  ]
}
