{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.0.1.aar",
          "url": "viewbinding-7.0.1.aar",
          "size": 2525,
          "sha512": "c0f8e5671648a5981d2d86e19a9ce1945299be75b0804da86bf2da9dcfa8ed7959832e05e33fffc10905503bd20e454af102c7366752604d8ee176266590c0cc",
          "sha256": "2ed9a869123aea51a23fff029334653ff77559be9a2b30ca80e93aa84e41bf03",
          "sha1": "7bb03805aa1a850fae3a68489bbb9f8bca2fa46e",
          "md5": "975681237b94efc93af0d0a51a6021c2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.0.1.aar",
          "url": "viewbinding-7.0.1.aar",
          "size": 2525,
          "sha512": "c0f8e5671648a5981d2d86e19a9ce1945299be75b0804da86bf2da9dcfa8ed7959832e05e33fffc10905503bd20e454af102c7366752604d8ee176266590c0cc",
          "sha256": "2ed9a869123aea51a23fff029334653ff77559be9a2b30ca80e93aa84e41bf03",
          "sha1": "7bb03805aa1a850fae3a68489bbb9f8bca2fa46e",
          "md5": "975681237b94efc93af0d0a51a6021c2"
        }
      ]
    }
  ]
}
