{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "tracker",
    "version": "30.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.0.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-30.0.1.jar",
          "url": "tracker-30.0.1.jar",
          "size": 39049,
          "sha512": "ec86816cdf3165e89b7f98dc812c0ab210492e69f86bc7447d1645ae841ea890f81fbebd8e8b78b7ad4c721b3383c91d19935b68209beebc4b8f9ad6752f18d3",
          "sha256": "0719425b8e248c123321b46a642f34e07531d51f74dfa01b33f7a13f77e43b32",
          "sha1": "7c6bec50f60d501c753235ea73c93121e932ea35",
          "md5": "4f8bf22fc0d44c6247f18ae583e33f47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.0.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-30.0.1.jar",
          "url": "tracker-30.0.1.jar",
          "size": 39049,
          "sha512": "ec86816cdf3165e89b7f98dc812c0ab210492e69f86bc7447d1645ae841ea890f81fbebd8e8b78b7ad4c721b3383c91d19935b68209beebc4b8f9ad6752f18d3",
          "sha256": "0719425b8e248c123321b46a642f34e07531d51f74dfa01b33f7a13f77e43b32",
          "sha1": "7c6bec50f60d501c753235ea73c93121e932ea35",
          "md5": "4f8bf22fc0d44c6247f18ae583e33f47"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracker-30.0.1-javadoc.jar",
          "url": "tracker-30.0.1-javadoc.jar",
          "size": 402626,
          "sha512": "1b1c731e7164a679efa1dd0c72f705063fdb9541fb76a49e9207a52d421cb3ac63b8b1bf077a27c300f998d631e69ee432aa45e1747fbd16bc393722dd64d929",
          "sha256": "cdf2a9abdfa45a78b916675e7ddbaf1848a93c1d0f864c2d6d1ddecddd4fa985",
          "sha1": "346ea2402c9f32ffdbe419339387d230523ede0d",
          "md5": "5cb25a857c42d100b4339b453e9d3a65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracker-30.0.1-sources.jar",
          "url": "tracker-30.0.1-sources.jar",
          "size": 18097,
          "sha512": "a2b23836c0b749a666c3a90280ff7ac7c61f400406ef9faeedb36d089a9b0e12130fd732f846a271209546aaac7194577c216e23c34192b458eabceff4474d5b",
          "sha256": "1b8dd1a4dd22923842d065557b80df7ce4924bac453ec401e4c81caee38f1631",
          "sha1": "90597dc1549be96cc35c7fbae8b30fa4affb88b7",
          "md5": "da58d38c9d10d27156f81afc1dffbd47"
        }
      ]
    }
  ]
}
