{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apksig",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apksig-7.0.1.jar",
          "url": "apksig-7.0.1.jar",
          "size": 392703,
          "sha512": "8ac63e4e19a499379ac24b571c5a2f722b5749a8b9c0d659bde87e24c4848ba602b3b52b80f418067dde0a5d80b82058e52f770a2b2e780cfc05690ce2f51781",
          "sha256": "dbb592349a3ddbe34f054e412a0af99b8fa9c56fa07aeaf2a8bb39314364daa3",
          "sha1": "2b406ad44b960bd38207fd05e8e624302ae609bb",
          "md5": "e98771d17ae3949d04b1233a6691e9eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apksig-7.0.1.jar",
          "url": "apksig-7.0.1.jar",
          "size": 392703,
          "sha512": "8ac63e4e19a499379ac24b571c5a2f722b5749a8b9c0d659bde87e24c4848ba602b3b52b80f418067dde0a5d80b82058e52f770a2b2e780cfc05690ce2f51781",
          "sha256": "dbb592349a3ddbe34f054e412a0af99b8fa9c56fa07aeaf2a8bb39314364daa3",
          "sha1": "2b406ad44b960bd38207fd05e8e624302ae609bb",
          "md5": "e98771d17ae3949d04b1233a6691e9eb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apksig-7.0.1-javadoc.jar",
          "url": "apksig-7.0.1-javadoc.jar",
          "size": 603131,
          "sha512": "317a2330b55ad753905e3ec699bba0cf217f67e9f4ac19d09705a8f0b65f5770f55b440be36162817e51182db0f105ddc7594a3161a99b98869cd9381cd1040f",
          "sha256": "cddd3597690e041a3cf8a9b24436238a78c6488a4a54e8237c51adc4297412b4",
          "sha1": "4e5a7d7c97d7ae285631974f817e7fb3b53ac256",
          "md5": "7f04947cc8f943a8b2628f3ab8e56549"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apksig-7.0.1-sources.jar",
          "url": "apksig-7.0.1-sources.jar",
          "size": 260326,
          "sha512": "71a7ac1fb6ef1d9a101f8da38129bf748a5160e5e39fcfabf2c9674198dae8c19aaedb77a75c5e94606fe1cd4dfef7916d3739ee8588fd5de203f17f66a76225",
          "sha256": "8842e40689bfddf7b40f2fe0f4bb6495e8f0d593f48663e60433b935ea4b4318",
          "sha1": "193141e353c0f9122918a6ef860000437e660d28",
          "md5": "b4f2f88ec9c0c26aa28d23df6f8d85c9"
        }
      ]
    }
  ]
}
